// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYLJaBPfp0K8LESQHAGtH6IiSVvrO0NLs',
    appId: '1:13329554062:web:28516bd4bfe1b08b5507df',
    messagingSenderId: '13329554062',
    projectId: 'hw4henry',
    authDomain: 'hw4henry.firebaseapp.com',
    storageBucket: 'hw4henry.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuIXwpKnD9SBhCn7hRBX4jfnR-6qD0p2Y',
    appId: '1:13329554062:android:ff218e5bea7d89f35507df',
    messagingSenderId: '13329554062',
    projectId: 'hw4henry',
    storageBucket: 'hw4henry.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB4zraOWalcV__8tysLtBj0OYjnLwk0MLM',
    appId: '1:13329554062:ios:f35b1d5c7cb1113d5507df',
    messagingSenderId: '13329554062',
    projectId: 'hw4henry',
    storageBucket: 'hw4henry.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB4zraOWalcV__8tysLtBj0OYjnLwk0MLM',
    appId: '1:13329554062:ios:f35b1d5c7cb1113d5507df',
    messagingSenderId: '13329554062',
    projectId: 'hw4henry',
    storageBucket: 'hw4henry.firebasestorage.app',
    iosBundleId: 'com.example.hw4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAYLJaBPfp0K8LESQHAGtH6IiSVvrO0NLs',
    appId: '1:13329554062:web:75dd8db25e6442fb5507df',
    messagingSenderId: '13329554062',
    projectId: 'hw4henry',
    authDomain: 'hw4henry.firebaseapp.com',
    storageBucket: 'hw4henry.firebasestorage.app',
  );
}
